# Generated by Django 3.2.3 on 2021-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('caption', models.CharField(max_length=10)),
                ('comments_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('engagement', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('hastag', models.CharField(max_length=20)),
                ('impact', models.IntegerField()),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
